development:
  adapter:  mysql
  encoding: utf8
  database: depot_development
  username: root
  password: nicom
  host:     localhost

test:
  adapter:  mysql
  encoding: utf8
  database: depot_test
  username: root
  password: nicom
  host:     localhost

production:
  adapter:  mysql
  encoding: utf8
  database: depot_production
  username: root
  password: nicom
  host:     localhost
